#Usuarios

###Registro nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "oscarcorrochanolopez@gmail.com",
  "password": "pruebaFinal123",
  "name": "Prueba",
  "lastname": "Final",
  "nif": "12345678X",
  "isAutonomous": false
}

###Validación de correo electrónico
POST http://localhost:3000/api/auth/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ3MjI4ZWNjZmExZWZiNWRjOWJkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTcwNDM1LCJleHAiOjE3NDYxNzc2MzV9.qnA_ji8Tq1L7R8PAKO_vjVUsA544xvxQ4_8fJh6JZXg

{
  "code": "425225"
}

###Login de usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "oscarcorrochanolopez@gmail.com",
  "password": "pruebaFinal123"
}

###Actualizar datos personales
PUT http://localhost:3000/api/users/68139c13d9ba9452565df9bb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE2MDcyLCJleHAiOjE3NDYxMjMyNzJ9.H-vFmrGM2Jxs4v67Upc5G-LbV7VqQHLzf28h3qeyNLk

{
  "name": "Prueba Actualizado",
  "lastname": "Final Actualizado",
  "nif": "87654321Z"
}

###Obtener usuario por token
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE2MTg0LCJleHAiOjE3NDYxMjMzODR9.9ayr1OYZBcL4WDkIuu1ojxORKUnKyQvSLKZiFQ7mzbI

###Actualizar datos de compañía
PATCH http://localhost:3000/api/users/update-company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE2MTg0LCJleHAiOjE3NDYxMjMzODR9.9ayr1OYZBcL4WDkIuu1ojxORKUnKyQvSLKZiFQ7mzbI

{
  "name": "Empresa Prueba Final",
  "cif": "B12345678",
  "address": "Dirección de la Prueba, Ciudad, 28232"
}

#Cambio de contraseña
###Solicitar codigo para recuperar contraseña
POST http://localhost:3000/api/auth/recover-password
Content-Type: application/json

{
  "email": "oscarcorrochanolopez@gmail.com"
}

###Cambiar contraseña
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsImlhdCI6MTc0NjExNjY3MCwiZXhwIjoxNzQ2MTE3MjcwfQ.-azJIZ-Eq3XFrEmIdLLCMRH-FnELr2XHiDdfsnMo0Ig",
  "newPassword": "NuevaPruebaFinal123"
}

###Invitar a un usuario
POST http://localhost:3000/api/users/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE3MTgyLCJleHAiOjE3NDYxMjQzODJ9.mXdeYDN-6s07OpP_h7W7zJNEbfwPyjFblnezQ6SNDx0

{
  "email": "usuarioInvitado@gmail.com"
}

###Eliminar usuario (soft-delete)
DELETE http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTM5YzEzZDliYTk0NTI1NjVkZjliYiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE3MzE3LCJleHAiOjE3NDYxMjQ1MTd9.TgBTomuINjblqH-1tXj0La3cuaIdHC_L51isLVNUZFc

###Eliminar usuario permanentemente (hard-delete)
DELETE http://localhost:3000/api/users/profile?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ5NTI5M2M4NDA5Y2M5YTQ2NTMzMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTc5NDAyLCJleHAiOjE3NDYxODY2MDJ9.Vgn25bLaYU4BaunGJesrDzHOW9bdzkBM4nniGsNKTAI


#Clientes

###Crear cliente
POST http://localhost:3000/api/client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ5NTY1MWI1MjZkYmQwNTU2NDc5NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTk2NDMxLCJleHAiOjE3NDYyMDM2MzF9.V-Gj6lviQc4GSS5jb_X6wr6HEiKtY-yjteYXdVaX4RY

{
  "name": "Cliente Prueba Final Final",
  "cif": "D12345673",
  "address": "Calle Prueba 236, Madrid",
  "email": "clientepruebafinalfinal@gmail.com",
  "phone": "123456781"
}

###Actualizar cliente
PUT http://localhost:3000/api/client/6813ac05d9ba9452565df9e6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

{
  "name": "Cliente Final Actualizado",
  "address": "Prueba Final Actializado, Madrid",
  "phone": "987654321"
}

###Listar clientes
GET http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ3MjI4ZWNjZmExZWZiNWRjOWJkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTcwNDM1LCJleHAiOjE3NDYxNzc2MzV9.qnA_ji8Tq1L7R8PAKO_vjVUsA544xvxQ4_8fJh6JZXg

###Obtener cliente por ID
GET http://localhost:3000/api/client/6813ac05d9ba9452565df9e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

###Archivar cliente (soft-delete)
DELETE http://localhost:3000/api/client/6813ac05d9ba9452565df9e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

###Eliminar cliente permanentemente (hard-delete)
DELETE http://localhost:3000/api/client/hard/6813ac05d9ba9452565df9e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

###Listar clientes archivados
GET http://localhost:3000/api/client/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

###Restaurar cliente archivado
PATCH http://localhost:3000/api/client/restore/6813ac05d9ba9452565df9e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTE5NjQ4LCJleHAiOjE3NDYxMjY4NDh9.Sqb568tII16YKSTX2Avce9H5AbPO5Gk79MAS96TrUSo

#Proyectos

###Crear proyecto
POST http://localhost:3000/api/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ5NTY1MWI1MjZkYmQwNTU2NDc5NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTk2NDMxLCJleHAiOjE3NDYyMDM2MzF9.V-Gj6lviQc4GSS5jb_X6wr6HEiKtY-yjteYXdVaX4RY

{
  "name": "Proyecto Prueba Final Final",
  "description": "Descripción del proyecto de prueba final final",
  "client": "6814d80301d43967c9706c53"
}

###Actualizar proyecto
PUT http://localhost:3000/api/project/681470f0eccfa1efb5dc9bd2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

{
  "name": "Proyecto prueba Final Actualizado",
  "description": "Nueva descripción del proyecto prueba Final",
  "client": "681470e5eccfa1efb5dc9bcf"
}

###Listar todos los proyectos
GET http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Obtener proyecto por ID
GET http://localhost:3000/api/project/6814728eeccfa1efb5dc9be7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Archivar proyecto (soft-delete)
DELETE http://localhost:3000/api/project/681470f0eccfa1efb5dc9bd2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Listar proyectos archivados
GET http://localhost:3000/api/project/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Eliminar proyecto permanentemente (hard delete)
DELETE http://localhost:3000/api/project/hard/6814728eeccfa1efb5dc9be7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Recuperar proyecto archivado
PATCH http://localhost:3000/api/project/restore/681470f0eccfa1efb5dc9bd2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

#Albaranes

###Crear albarán con una sola entrada
POST http://localhost:3000/api/deliverynote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTQ5NTY1MWI1MjZkYmQwNTU2NDc5NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTk2NDMxLCJleHAiOjE3NDYyMDM2MzF9.V-Gj6lviQc4GSS5jb_X6wr6HEiKtY-yjteYXdVaX4RY

{
  "type": "hours",
  "client": "6814d80301d43967c9706c53",
  "project": "6814d82501d43967c9706c56",
  "entries": [
    {
      "description": "Albarán para prueba final final",
      "quantity": 8,
      "unit": "horas"
    }
  ]
}

###Crear albarán con varias entradas
POST http://localhost:3000/api/deliverynote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

{
  "type": "materials",
  "client": "68147273eccfa1efb5dc9be4",
  "project": "68147a60eccfa1efb5dc9c07",
  "entries": [
    {
      "description": "Material A",
      "quantity": 10,
      "unit": "unidades"
    },
    {
      "description": "Material B",
      "quantity": 5,
      "unit": "metros"
    },
    {
      "description": "Albarán para prueba final con varias entradas",
      "quantity": 8,
      "unit": "horas"
    }
  ]
}

###Listar todos los albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Obtener albarán por ID
GET http://localhost:3000/api/deliverynote/68147a86eccfa1efb5dc9c0a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Descargar albarán en PDF
GET http://localhost:3000/api/deliverynote/pdf/68147acdeccfa1efb5dc9c0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc

###Firmar albarán
PATCH http://localhost:3000/api/deliverynote/sign/68147acdeccfa1efb5dc9c0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="firma.png"
Content-Type: image/png

< ./firma.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###Eliminar albarán
DELETE http://localhost:3000/api/deliverynote/68147a86eccfa1efb5dc9c0a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTNhM2Q3ZDliYTk0NTI1NjVkZjlkZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ2MTY5OTcwLCJleHAiOjE3NDYxNzcxNzB9.KUJJOnm9_YzTyGVHdTcqOaL6AKOYAAkcv256c90P0Wc


